<!-- BEGIN PAGE TITLE-->
<section>
    <h3 class="page-title"> Profile
        <small>Edit Profile</small>
    </h3>
</section>
<!-- END PAGE TITLE-->

<!--BEGIN CONTENT-->
<?php echo '<div class="row"><div class="col-sm-offset-3 col-sm-6">' . $this->getContent() . '</div></div>'; ?>

<div class="portlet light bordered">
    <div class="portlet-title">
        <div class="caption">
            <i class="icon-equalizer font-red-sunglo"></i>
            <span class="caption-subject font-red-sunglo bold uppercase">Profile</span>
            <span class="caption-helper">Setup</span>
        </div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <form id="login-form" action="<?php echo $this->url->get('users/bprofile'); ?>" method="post" class="form-horizontal">
            <div class="form-body">
                <div class="form-group">
                    <label class="col-md-3 control-label">First name</label>
                    <div class="col-md-4">
                        <input type="text" name="first_name" class="form-control" placeholder="First Name" <?php if(isset($object->first_name)) echo 'value="' .$object->first_name .'" ';?>>
                        <span class="help-block" style="">Please enter your first name.</span>
                        <?php if(isset($formMessages['first_name'])) echo '<span class="help-block" style="color: crimson;">' .$formMessages['first_name'] .'</span>' ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">Last name</label>
                    <div class="col-md-4">
                        <input type="text" name="last_name" class="form-control" placeholder="Last Name" <?php if(isset($object->last_name)) echo 'value="' .$object->last_name .'" ';?>>
                        <span class="help-block" style="">Please enter your last name.</span>
                        <?php if(isset($formMessages['last_name'])) echo '<span class="help-block" style="color: crimson;">' .$formMessages['last_name'] .'</span>' ?>
                    </div>
                </div>
            </div>
            <div class="form-actions">
                <div class="row">
                    <div class="col-md-offset-3 col-md-4">
                        <button type="submit" class="btn green">Submit</button>
                        <button type="button" class="btn default">Cancel [remove]</button>
                    </div>
                </div>
            </div>
        </form>
        <!-- END FORM-->
    </div>
</div>
<!--END CONTENT-->
